package api

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"unicode/utf8"

	"github.com/gin-gonic/gin"

	"dps150-web/backend/internal/storage"
)

// tokenMaxName bounds the name field, matching the ApiToken.Name column.
const tokenMaxName = 128

// tokenStore is the storage surface the token routes and authGate's Bearer
// check consume; *storage.Storage implements it. Handlers treat a nil
// tokenStore as storage never having been configured (503).
type tokenStore interface {
	ListTokens(ctx context.Context) ([]storage.ApiToken, error)
	CreateToken(ctx context.Context, name, scope string) (string, storage.ApiToken, error)
	DeleteToken(ctx context.Context, id int64) error
	LookupToken(ctx context.Context, secret string) (storage.ApiToken, error)
}

// tokenDTO mirrors the ApiToken object of API contract v3 (F-020): metadata
// only, never the secret.
type tokenDTO struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Scope      string `json:"scope"`
	CreatedAt  int64  `json:"createdAt"`
	LastUsedAt *int64 `json:"lastUsedAt"`
}

func tokenJSON(t storage.ApiToken) tokenDTO {
	return tokenDTO{
		ID:         t.ID,
		Name:       t.Name,
		Scope:      t.Scope,
		CreatedAt:  t.CreatedAt,
		LastUsedAt: t.LastUsedAt,
	}
}

// createTokenResponseDTO is the 201 response of POST /api/v1/tokens: the
// ApiToken fields plus the secret, shown this one time only.
type createTokenResponseDTO struct {
	Token string `json:"token"`
	tokenDTO
}

// requireTokens guards the storage dependency: a backend started without a
// usable storage configuration answers the same 503 the contract prescribes
// for a down database.
func requireTokens(c *gin.Context, store tokenStore) bool {
	if store == nil {
		writeError(c, http.StatusServiceUnavailable, "storage_unavailable",
			"storage is not configured")
		return false
	}
	return true
}

// tokenID parses the {id} path parameter. An unparseable id cannot match any
// token, so it reports 404 token_not_found.
func tokenID(c *gin.Context) (int64, bool) {
	id, err := strconv.ParseInt(c.Param("id"), 10, 64)
	if err != nil || id <= 0 {
		writeError(c, http.StatusNotFound, "token_not_found", "token not found")
		return 0, false
	}
	return id, true
}

// writeTokenError maps storage errors of the token routes onto the
// contract's error responses.
func writeTokenError(c *gin.Context, err error) {
	switch {
	case errors.Is(err, storage.ErrUnavailable):
		writeError(c, http.StatusServiceUnavailable, "storage_unavailable",
			"database is unavailable")
	case errors.Is(err, storage.ErrNotFound):
		writeError(c, http.StatusNotFound, "token_not_found", "token not found")
	case errors.Is(err, storage.ErrInvalidScope):
		writeError(c, http.StatusBadRequest, "invalid_token", `scope must be "read" or "control"`)
	default:
		writeError(c, http.StatusInternalServerError, "internal", err.Error())
	}
}

// parseCreateTokenRequest validates the request body of POST /tokens and
// returns the name and scope to store. On failure it writes 400
// invalid_token and reports ok=false. The secret itself is generated by the
// storage layer, never taken from the request.
func parseCreateTokenRequest(c *gin.Context) (name, scope string, ok bool) {
	fail := func(msg string) (string, string, bool) {
		writeError(c, http.StatusBadRequest, "invalid_token", msg)
		return "", "", false
	}
	var req struct {
		Name  *string `json:"name"`
		Scope *string `json:"scope"`
	}
	if err := c.ShouldBindJSON(&req); err != nil {
		return fail("request body must be a JSON object with name and scope")
	}
	if req.Name == nil {
		return fail("name is required")
	}
	name = strings.TrimSpace(*req.Name)
	if name == "" || utf8.RuneCountInString(name) > tokenMaxName {
		return fail(fmt.Sprintf("name must be non-empty and at most %d characters", tokenMaxName))
	}
	if req.Scope == nil {
		return fail(`scope is required ("read" or "control")`)
	}
	scope = *req.Scope
	if scope != storage.ScopeRead && scope != storage.ScopeControl {
		return fail(`scope must be "read" or "control"`)
	}
	return name, scope, true
}

// listTokens handles GET /api/v1/tokens: every token's metadata, never the
// secret (API contract v3, F-020). Restricted to Authelia by requireAuthelia
// on the route (ADR-006): see auth.go.
func listTokens(store tokenStore) gin.HandlerFunc {
	return func(c *gin.Context) {
		if !requireTokens(c, store) {
			return
		}
		items, err := store.ListTokens(c.Request.Context())
		if err != nil {
			writeTokenError(c, err)
			return
		}
		dtos := make([]tokenDTO, 0, len(items))
		for _, t := range items {
			dtos = append(dtos, tokenJSON(t))
		}
		c.JSON(http.StatusOK, gin.H{"items": dtos})
	}
}

// createToken handles POST /api/v1/tokens: generates a new bearer secret and
// returns it once, alongside its metadata. Restricted to Authelia (see
// listTokens).
func createToken(store tokenStore) gin.HandlerFunc {
	return func(c *gin.Context) {
		if !requireTokens(c, store) {
			return
		}
		name, scope, ok := parseCreateTokenRequest(c)
		if !ok {
			return
		}
		secret, tok, err := store.CreateToken(c.Request.Context(), name, scope)
		if err != nil {
			writeTokenError(c, err)
			return
		}
		c.JSON(http.StatusCreated, createTokenResponseDTO{Token: secret, tokenDTO: tokenJSON(tok)})
	}
}

// deleteToken handles DELETE /api/v1/tokens/{id}: revokes the token
// immediately (LookupToken re-reads the database on every call, no cache
// outlives the request). Restricted to Authelia (see listTokens).
func deleteToken(store tokenStore) gin.HandlerFunc {
	return func(c *gin.Context) {
		if !requireTokens(c, store) {
			return
		}
		id, ok := tokenID(c)
		if !ok {
			return
		}
		if err := store.DeleteToken(c.Request.Context(), id); err != nil {
			writeTokenError(c, err)
			return
		}
		c.Status(http.StatusNoContent)
	}
}
