apiVersion: v1
kind: Service
metadata:
  name: {{ include "dps150-web.backend.fullname" . }}
  labels:
    {{- include "dps150-web.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dps150-web.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dps150-web.frontend.fullname" . }}
  labels:
    {{- include "dps150-web.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dps150-web.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
