package storage

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"time"

	"gorm.io/gorm"
)

// Token scopes (API contract v3, F-020 / ADR-006). Mutations (PUT/POST/
// DELETE) under /api require ScopeControl; reads accept either.
const (
	ScopeRead    = "read"
	ScopeControl = "control"
)

// ErrInvalidScope is returned by CreateToken for a scope other than
// ScopeRead or ScopeControl.
var ErrInvalidScope = errors.New("storage: invalid token scope")

// lastUsedThrottle bounds how often LookupToken restamps LastUsedAt: a
// bearer-authenticated caller may poll several times a second, and
// restamping on every request would mean a write per request. One update
// per window is enough for the metadata's purpose (operators eyeballing
// "is this token still in use").
const lastUsedThrottle = time.Minute

// ApiToken is an API access token (API contract v3, F-020): bearer-
// authenticated per ADR-006, scoped to ScopeRead or ScopeControl. Only the
// SHA-256 hash of the secret is ever persisted; the secret itself is
// generated by CreateToken, returned once in its response and never stored
// or logged. The model is feature-owned: cmd/server registers it through
// Config.Models.
type ApiToken struct {
	ID    int64  `gorm:"primaryKey;autoIncrement"`
	Name  string `gorm:"size:128"`
	Scope string `gorm:"size:16"`
	// TokenHash is the lowercase-hex SHA-256 of the secret. json:"-" keeps it
	// out of any accidental direct marshaling of this struct; API handlers
	// additionally map to a dedicated DTO that never mentions it.
	TokenHash  string `gorm:"uniqueIndex;size:64" json:"-"`
	CreatedAt  int64  `gorm:"autoCreateTime:milli"`
	LastUsedAt *int64
}

// newTokenSecret generates the bearer secret handed to the caller once:
// "dps_" followed by the base64url (unpadded) encoding of 32 random bytes.
func newTokenSecret() (string, error) {
	buf := make([]byte, 32)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("generate token secret: %w", err)
	}
	return "dps_" + base64.RawURLEncoding.EncodeToString(buf), nil
}

// hashTokenSecret returns the lowercase-hex SHA-256 of secret, the only form
// ever persisted.
func hashTokenSecret(secret string) string {
	sum := sha256.Sum256([]byte(secret))
	return hex.EncodeToString(sum[:])
}

// CreateToken generates a new bearer secret, stores its SHA-256 hash under
// name/scope and returns the secret alongside the stored row. The secret is
// NOT recoverable afterwards: callers must surface it to the operator now.
// scope must be ScopeRead or ScopeControl (ErrInvalidScope otherwise).
// ErrUnavailable is returned while the database is down.
func (s *Storage) CreateToken(ctx context.Context, name, scope string) (string, ApiToken, error) {
	if scope != ScopeRead && scope != ScopeControl {
		return "", ApiToken{}, ErrInvalidScope
	}
	db, err := s.DB()
	if err != nil {
		return "", ApiToken{}, err
	}
	secret, err := newTokenSecret()
	if err != nil {
		return "", ApiToken{}, err
	}
	tok := ApiToken{Name: name, Scope: scope, TokenHash: hashTokenSecret(secret)}
	if err := db.WithContext(ctx).Create(&tok).Error; err != nil {
		return "", ApiToken{}, fmt.Errorf("create token %q: %w", name, err)
	}
	return secret, tok, nil
}

// ListTokens returns every token's metadata (never the secret, which is
// never stored) ordered by creation time. It returns ErrUnavailable while
// the database is down.
func (s *Storage) ListTokens(ctx context.Context) ([]ApiToken, error) {
	db, err := s.DB()
	if err != nil {
		return nil, err
	}
	var items []ApiToken
	if err := db.WithContext(ctx).Order("created_at").Find(&items).Error; err != nil {
		return nil, fmt.Errorf("list tokens: %w", err)
	}
	return items, nil
}

// DeleteToken removes the token with the given id, revoking it immediately:
// the next LookupToken for its secret misses (no cache outlives the
// request). It returns ErrNotFound when there is nothing to delete and
// ErrUnavailable while the database is down.
func (s *Storage) DeleteToken(ctx context.Context, id int64) error {
	db, err := s.DB()
	if err != nil {
		return err
	}
	res := db.WithContext(ctx).Delete(&ApiToken{}, id)
	if res.Error != nil {
		return fmt.Errorf("delete token %d: %w", id, res.Error)
	}
	if res.RowsAffected == 0 {
		return ErrNotFound
	}
	return nil
}

// LookupToken hashes secret and returns the matching token, restamping
// LastUsedAt when it has not been touched in the last minute (best-effort:
// a failure to restamp does not fail the lookup, since the hash match
// already establishes the token is valid). It returns ErrNotFound for an
// unknown or revoked secret and ErrUnavailable while the database is down
// -- in both cases the caller cannot be authenticated by this method, and
// callers MUST NOT treat ErrUnavailable as "let the bearer request through
// anyway": with nothing to validate the hash against, the request should be
// rejected the same as an invalid secret (see api.authGate).
func (s *Storage) LookupToken(ctx context.Context, secret string) (ApiToken, error) {
	db, err := s.DB()
	if err != nil {
		return ApiToken{}, err
	}
	hash := hashTokenSecret(secret)
	var tok ApiToken
	if err := db.WithContext(ctx).Where("token_hash = ?", hash).First(&tok).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return ApiToken{}, ErrNotFound
		}
		return ApiToken{}, fmt.Errorf("lookup token: %w", err)
	}
	s.touchTokenLastUsed(ctx, db, tok)
	return tok, nil
}

// touchTokenLastUsed restamps tok's LastUsedAt in the background window
// described by lastUsedThrottle. Failures are logged and swallowed: this is
// metadata, not part of the auth decision, and must never turn a valid
// lookup into a failed one.
func (s *Storage) touchTokenLastUsed(ctx context.Context, db *gorm.DB, tok ApiToken) {
	now := time.Now().UnixMilli()
	if tok.LastUsedAt != nil && now-*tok.LastUsedAt < lastUsedThrottle.Milliseconds() {
		return
	}
	if err := db.WithContext(ctx).Model(&ApiToken{}).Where("id = ?", tok.ID).
		Update("last_used_at", now).Error; err != nil {
		s.logger.Warn("token last_used_at update failed", "id", tok.ID, "error", err)
	}
}
